-- local 프로파일(jdbc:h2:mem:local-test) 전용 샘플 데이터.
-- spring.sql.init.data-locations 로 명시한 프로파일에서만 실행된다.
-- created_at/modified_at 는 TIMESTAMP WITH TIME ZONE 컬럼에 맞춰 명시적으로 캐스팅한다.
INSERT INTO tb_list_view_sample (id, name, status, category, frequency, created_at, modified_at) VALUES
  (1,  'Daily Traffic Report',      'CREATED',  'BASIC',   'EVERY_DAY', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (2,  'Weekly Threat Summary',     'CREATED',  'UNIFIED', 'EVERY_WEEK', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (3,  'Monthly Compliance Audit',  'PENDING',  'UNIFIED', 'EVERY_MONTH_DAY', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (4,  'Ad-hoc Traffic Query',      'CREATING', 'QUERY',   'IMMEDIATE', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (5,  'Yearly Capacity Plan',      'CREATED',  'BASIC',   'EVERY_YEAR', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (6,  'Nightly Backup Check',      'FAILED',   'BASIC',   'SPECIFIC_TIME', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (7,  'Legacy Traffic Archive',    'DELETED',  'QUERY',   'EVERY_DAY', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (8,  'Quarterly Threat Review',   'PENDING',  'UNIFIED', 'EVERY_MONTH_DAY', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (9,  'Ad-hoc Security Scan',      'CREATED',  'QUERY',   'IMMEDIATE', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE)),
  (10, 'Annual Compliance Report',  'CREATED',  'BASIC',   'EVERY_YEAR', CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE), CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE));

ALTER SEQUENCE seq_list_view_sample_id RESTART WITH 11;
