---
version: "2.1"
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
        #- PUID=1000
        #- PGID=1000
        #- TZ=Etc/UTC
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
    volumes:
      - /etc/syslog-ng:/config
      - /tmp/log:/var/log
    network_mode: host
    #ports:
    #  - 5514:5514/udp
    #  - 6601:6601/tcp
    #  - 6514:6514/tcp
    restart: unless-stopped
