spring.profiles.active: dev
logging.config: classpath:log4j2-${spring.profiles.active}.xml

spring.batch.job.enabled: false
# spring.batch.job.name: multiStepJob
# spring.batch.job.name: singleStepjob
