spring.profiles.active: dev
spring.batch.job.enabled: false
# spring.datasource:
#   hikari:
#     minimum-idle: 10
#     maximum-pool-size: 50
#     idle-timeout: 600000
#     pool-name: BATCH-OLTP-POOL
#     max-lifetime: 1800000
#     connection-timeout: 30000

logging.config: classpath:log4j2-${spring.profiles.active}.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml

job.enabler.sample: true
