version: '3'
services:
  postgres:
    container_name: test-postgres
    image: postgres:latest
    environment:
        #- POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dvdrental
    ports:
      - "5430:5432"
    restart: unless-stopped
    volumes:
      - pgsdata:/var/lib/postgresql/data
      - ../init:/init
volumes:
  pgsdata:
