# common appliction properies:
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

# profile - https://docs.spring.io/spring-boot/reference/features/profiles.html

spring:
  profiles:
    group:
      production:
        - prod

# spring.profiles.active: dev,hsqldb
spring.profiles.default: dev
spring.profiles.active: dev
spring.threads.virtual.enabled: true
server.port: 8181

logging.config: classpath:log4j2-${spring.profiles.active}.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/**/*.xml
  # DAO(result type) package
  type-aliases-package: com.example.springwebex.model
